### ISSUE TITLE
PHP Catchable Fatal Error: Argument 2 passed to ...

### ISSUE THREAD

**Issue by webdev2027** [Zillion01/jpfaq#14]
Hi. I use `TYPO3 7.6.27 LTS` with `PHP 5.5`. Today I've updated `jpfaq` from 8.5.2 to 8.8.1.
After update via Extension Manager, I've got the following error:

`PHP Catchable Fatal Error: Argument 2 passed to Jp\Jpfaq\Domain\Repository\QuestionRepository::findQuestionsWithConstraints() must be an instance of Jp\Jpfaq\Domain\Repository\bool, integer given, called in C:\www\myproject\typo3conf\ext\jpfaq\Classes\Controller\QuestionController.php on line 62 and defined in C:\www\myproject\typo3conf\ext\jpfaq\Classes\Domain\Repository\QuestionRepository.php line 37`

What happend? Should I de- and reinstall `jpfaq` completely?
Try to fix ... cleared Cache, `rm- rf typo3temp/*` and database compare ...  nothing happens?!

Thanks for your help.

**Comment by Zillion01** [comment]
Hi, this seems to be a bug which occurs on PHP5.5, because I cannot reproduce it.

Could you try change line 61 in /typo3conf/ext/jpfaq/Classes/Controller/QuestionController.phpQuestionController.php

from 
`$excludeAlreadyDisplayedQuestions = intval($this>settings['excludeAlreadyDisplayedQuestions']);`

to 
`$excludeAlreadyDisplayedQuestions = (bool)($this>settings['excludeAlreadyDisplayedQuestions']);`

After that clear cache

**Comment by webdev2027** [comment]
Hello. Now I've got an 500 error, after change the line 62, like you've wrote.
Ok, doesen't matter. I try to update my PHP-version. Thanks.
