### ISSUE TITLE
Table 'tx_jpfaq_domain_model_ttcontent' doesn't exist

### ISSUE THREAD

**Issue by geri777** [Zillion01/jpfaq#28]
In Version 9.5.3 with Typo3 9.5.11 I get the following error in the FE after connecting the plugin with the FAQ record page:
`Table 'tx_jpfaq_domain_model_ttcontent' doesn't exist`

**Comment by Zillion01** [comment]
That's weird because no bugs are reported with jpFaq 9.5.3. Maybe try reinstall. You can test on a new TYPO3 9.5 installation with only for example the introduction package. 

I would however always work with latest TYPO3 9.5 version, currently 9.5.21. Though jpFaq 9.5.3 is bug free, jpFaq version 10.4.0 also works with TYPO3 9.5

**Comment by geri777** [comment]
I have updated Typo3 to 9.5.22, completely removed the extension and installed it again. Same problem again. 

`"exception":"Doctrine\\DBAL\\Driver\\Mysqli\\MysqliException: Table 'svk_typo3_2019.tx_jpfaq_domain_model_ttcontent' doesn't exist in /var/www/xxx/typo3_src-9.5.22/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php`

**Comment by Zillion01** [comment]
I see others have some issues too https://forge.typo3.org/issues/75399

Not sure what to do, since I never encountered this.

**Comment by geri777** [comment]
Many thanks for the link to the bug. I have invested 2-3 hours to test and debug but have not been successfull yet. None of the advices from the users have worked.

**Comment by Zillion01** [comment]
Did you try an empty site with only the introduction package, then you can maybe find out if it's a TYPO3 config or maybe PHP / MySQL related.
